config {
    type: "table",
    tags: ["FULL", "FILTER_DATA"]
}

SELECT
  trip_start_timestamp,
  trip_end_timestamp,
  dropoff_location,
  trip_year,
  zip.city dropoff_city,
  zip.county dropoff_county,
  zip.state_code dropoff_state_code,
  zip.zip_code dropoff_zip_code
FROM
  ${ref("taxi_trips_2024")} taxi_trips
LEFT JOIN
  ${ref("zip_codes")} zip
ON
  ST_CONTAINS(zip.zip_code_geom, dropoff_location)
